question_data =[
    {"text": "The Eiffel Tower was originally intended to be dismantled after 20 years.", "answer": "True"},
    {"text": "The first operating system to use a graphical user interface was Windows 3.1.", "answer": "False" },
    {"text": "The Trojan Horse, used in Greek mythology, was a real weapon in the ancient war with Troy.", "answer": "False"},
    {"text": "The Hubble Space Telescope was launched in 1990.", "answer": "True"},
    {"text": "The Moon is slowly drifting away from the Earth at a rate of about 3.8 centimeters per year.", "answer": "True"},
    {"text": "The total number of atoms in a single human body is roughly equal to the number of stars in the Milky Way galaxy.", "answer": "True"},
    {"text": "The largest desert in the world is the Sahara Desert.", "answer": "False" },
    {"text": "The Soviet Union was the first country to land a human on the Moon.", "answer": "False" },
    {"text": "The only letter that doesn’t appear in the periodic table of elements is J.", "answer": "True"},
    {"text": "Marie Curie was the first person to win two Nobel Prizes in different scientific fields.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False" },
    {"text": "The human genome project was completed in 2003, mapping all of the genes in human DNA.", "answer": "True"},
    {"text": "The Great Wall of China is over 13,000 miles long.", "answer": "True"},
    {"text": "The first computer virus was created in 1986.", "answer": "True"},
    {"text": "Julius Caesar was the first emperor of Rome.", "answer": "False"},
    {"text": "The Eiffel Tower is made of steel, not iron.", "answer": "True"},
    {"text": "The first computer virus was named ‘Creeper’ and was created in the 1980s.", "answer": "True"},
    {"text": "The Amazon River is longer than the Nile River.", "answer": "False" },
    {"text": "The largest volcano in the solar system is on Mars and is called Olympus Mons.", "answer": "True"},
    {"text": "Alan Turing is considered the father of modern computer science.", "answer": "True"},
    {"text": "There is no indigenous population in the United States.", "answer": "False" },
    {"text": "In 1957, the Soviet Union launched Sputnik 1, the first artificial satellite.", "answer": "True"},
    {"text": "The human heart beats an average of 100,000 times per day.", "answer": "True"},
    {"text": "The first successful human heart transplant was performed in 1970.", "answer": "False" },
    {"text": "The moon orbits the Earth in a perfect circle.", "answer": "False" },
    {"text": "The first video game ever created was Pong.", "answer": "False" },
    {"text": "The tallest building in the world is located in New York City.", "answer": "False" },
    {"text": "The speed of light is approximately 300,000 kilometers per second.", "answer": "True"},
    {"text": "The atomic number of hydrogen is 2.", "answer": "False" },
    {"text": "Humans and chimpanzees share about 98% of their DNA.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Pablo Picasso.", "answer": "False" },
    {"text": "The shortest war in history was between Britain and Zanzibar in 1896, lasting 38 minutes.", "answer": "True"},
    {"text": "The first person to suggest the Earth was round was Aristotle.", "answer": "True"},
    {"text": "Thomas Edison invented the light bulb.", "answer": "False" },
    {"text": "A black hole's gravitational pull is so strong that not even light can escape from it.", "answer": "True"},
    {"text": "The planet Venus is the hottest planet in the solar system, even hotter than Mercury.", "answer": "True"},
    {"text": "Cleopatra was the last active ruler of the Ptolemaic Kingdom of Egypt.", "answer": "True"},
    {"text": "The tallest mountain in the solar system, Olympus Mons, is on Earth.", "answer": "False" },
    {"text": "Leonardo da Vinci was an architect, painter, and inventor.", "answer": "True"},
    {"text": "The Eiffel Tower was designed by the artist Gustave Eiffel, not an architect.", "answer": "False"},
    {"text": "The United Kingdom consists of England, Wales, Scotland, and Northern Ireland.", "answer": "True"},
    {"text": "The first email was sent in 1971 by Ray Tomlinson.", "answer": "True"},
    {"text": "The speed of sound is faster in water than in air.", "answer": "True"},
    {"text": "The Pacific Ocean is the deepest ocean in the world.", "answer": "True"},
    {"text": "The first person to swim across the English Channel was an American named Captain Matthew Webb.", "answer": "True"},
    {"text": "Albert Einstein was awarded the Nobel Prize in Physics for his theory of relativity.", "answer": "False" },
    {"text": "The Great Fire of London happened in 1666.", "answer": "True"},
    {"text": "The ancient Romans invented concrete.", "answer": "True"},
    {"text": "The first computer mouse was invented by Bill Gates.", "answer": "False" },
    {"text": "Venus is the only planet in our solar system that rotates in the opposite direction of most planets.", "answer": "True"}
]

